url: 'https://api.myhost.com'

auth:
  type: form
  path: /auth
  user_key: username
  pass_key: password
  token: header
  header_key: "X-API-AUTH-TOKEN"

commands:
  - name: user_list
    path: /users

